### ISSUE TITLE
Add ACR to pattern module

### ISSUE THREAD

**Issue by vyta** [Azure/terraform-azurerm-avm-ptn-ai-platform-baseline#9]

**Comment by vyta** [comment]
@Nepomuceno looks like a container registry is already deployed as part of the pattern, what is left on this issue?

**Comment by Nepomuceno** [comment]
@vyta 
The ACR that is created right now it is being created by the resource module and not part as the pattern module so it is onot secure and private by default it gets the defaults of the resource module. We need to create it from the patter in order to control it better.
